const data = [
  {
    latinName: "Agaricus xanthodermus",
    commonName: "Yellow Staining Mushroom",
    articleRef: "https://www.rbg.vic.gov.au/science/herbarium-and-resources/identification-and-information-services/agaricus-xanthodermus",
    imageSrc: require("./images/agaricus_xanthodermus.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjtl_6dx4flAhWPbX0KHSNjDnkQjB16BAgBEAM&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3A2011-10-13_Agaricus_xanthodermus_Genev_181971.jpg&psig=AOvVaw1t2jADw1rOVgkJETlWlgiV&ust=1570448489379808",
    characteristics: [
      "annulus present on the stipe",
      "dark purplish brown spore print",
      "cap and stem stain bright yellow on bruising or scratching",
      "smells like disinfectant",
    ],
    symptoms: [
      "nausea",
      "stomach cramps",
      "diarrhoea",
      "vomiting",
    ],
    distribution: [
      "SA",
      "QLD",
      "NSW",
      "VIC",
      "TAS"
    ]
  },
  {
    latinName: "Amanita phalloides",
    commonName: "Death Cap",
    articleRef: "https://www.anbg.gov.au/fungi/deathcap.html",
    imageSrc: require("./images/amanita_phalloides.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiBsaf344XlAhVQdCsKHZSWCGEQjB16BAgBEAM&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AAmanita_phalloides_Kiev3.jpg&psig=AOvVaw2BMx8xvXGWETbhkDpxCx9h&ust=1570387549476194",
    characteristics: [
      "smooth, yellow-ish green to olive-brown cap",
      "membranous skirt on stem",
      "a cup-like volva around the base of the stem",
      "white spore print and gills",
    ],
    symptoms: [
      "stomach pain",
      "vomiting",
      "diarrhoea",
      "jaundice (terminal)",
      "after 1-2 week, death by liver failure, sometimes also kidney failure"
    ],
    distribution: [
      "ACT",
      "VIC",
      "SA",
    ],
  },
  {
    latinName: "Omphalotus nidiformis",
    commonName: "Ghost Fungus",
    articleRef: "https://bie.ala.org.au/species/880abd7a-b60f-44b6-8c08-ea72f832d2e0",
    imageSrc: require("./images/omphalotus_nidiformis.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjhm5Tj_YblAhWCXSsKHeF9AMAQjB16BAgBEAM&url=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fgugglebun%2F16368277785&psig=AOvVaw07RhrKQv25_D28GZnZdtY1&ust=1570428890838212",
    characteristics: [
      "glows in the dark(!)",
      "fan/funnel shaped fruit bodies, cream-coloured caps",
      "gills run down the length of the stipe",
    ],
    symptoms: [
      "vomiting that lasts for several hours, 30-120 mins after consumption",
    ],
    distribution: [
      "WA",
      "QLD",
      "SA",
      "TAS",
      "NSW",
    ],
  },
  {
    latinName: "Chlorophyllum brunneum",
    commonName: "Shaggy Parasol",
    articleRef: "https://www.inaturalist.org/taxa/58693-Chlorophyllum-brunneum",
    imageSrc: require("./images/chlorophyllum_brunneum.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjeo9-b_oblAhUSeisKHVXcD-EQjB16BAgBEAM&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3A2010-10-10_Chlorophyllum_brunneum.jpg&psig=AOvVaw0K6R80rpZOlxqr1JNTLQr0&ust=1570429020352181",
    characteristics: [
      "thick brown scales and protruberances on white cap",
      "white gill and spore print",
      "slender stipe, bulbous base",
      "reddish discolouration and pungent odour when cut"
    ],
    symptoms: [
      "gastric upset if eaten raw",
    ],
    distribution: [
      "WA",
      "SA",
      "VIC",
      "NSW",
      "QLD",
    ],
  },
  {
    latinName: "Scleroderma citrinum",
    commonName: "Earthball",
    articleRef: "https://bie.ala.org.au/species/4a447b53-bc9e-4e0e-ba17-ff4127bb3f9f",
    imageSrc: require("./images/scleroderma.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiugJLj_oblAhWPbysKHTi_AXMQjB16BAgBEAM&url=https%3A%2F%2Fwww.geograph.org.uk%2Fphoto%2F1474090&psig=AOvVaw2TXsojt-73IjfIGuJV39l1&ust=1570429157630897",
    characteristics: [
      "round",
      "dark interior",
      "thick outer wall, usually ochre yellow with irregular walls",
    ],
    symptoms: [
      "gastrointestinal distress from ingestion",
      "lacrimation, rhinitis, rhinorrhea, and conjunctivitis from exposure to spores"
    ],
    distribution: [
      "QLD",
      "WA",
      "VIC",
      "NSW",
    ],
  },
  {
    latinName: "Hebeloma crustuliniforme",
    commonName: "Poison Pie",
    articleRef: "https://bie.ala.org.au/species/45a4b5dd-cf5d-47d3-aad8-25c9908ced5f",
    imageSrc: require("./images/hebeloma_crustuliniforme.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiw35K0_4blAhXafSsKHbQ-CvwQjB16BAgBEAM&url=https%3A%2F%2Fpl.wikipedia.org%2Fwiki%2FPlik%3AHebeloma_crustuliniforme_a1_(2).JPG&psig=AOvVaw3QDj_saJtLGJf--JwcaRb6&ust=1570429295275991",
    characteristics: [
      "buff to pale tan cap, convex with inrolled cap margin",
      "pale grey-brown gills with droplets when moist",
      "no ring",
      "radish-like smell and bitter taste",
    ],
    symptoms: [
      "vomiting",
      "diarrhoea",
      "colicky abdominal pain",
    ],
    distribution: [
      "WA",
      "VIC",
      "NSW",
    ],
  },
  {
    latinName: "Podostroma cornu-damae",
    commonName: "Poison Fire Coral",
    articleRef: "https://bie.ala.org.au/species/NZOR-6-90448",
    imageSrc: require("./images/podostroma_cornu-damae.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiK77fRg4flAhXRfn0KHfmQCw0QjB16BAgBEAM&url=https%3A%2F%2Fameblo.jp%2Fdoppel611%2Fentry-11005627991.html&psig=AOvVaw1DA3FME6aHE1wToocvv50m&ust=1570430452266149",
    characteristics: [
      "red and scary (obviously)",
      "phialides arranged in tufts with narrow angles at the top",
      "roughly spherical conidia with truncate base in each spore, pale green in colour",
      "almost smooth surface",
    ],
    symptoms: [
      "stomach pains",
      "change in percention",
      "decrease of leukocytes and thrombocytes",
      "peeling face skin",
      "hair loss",
      "shrinking cerebellum, resulting in speech impediment and problems with voluntary movement",
      "possibly multiple organ failure (kidney, liver necrosis, disseminated intravascular coagulation)",
      "possibly hemophagocytosis"
    ],
    distribution: [
      "Recently found in QLD",
    ],
  },
  {
    latinName: "Chlorophyllum molybdites",
    commonName: "Green-gilled Parasol",
    articleRef: "https://bie.ala.org.au/species/4e0080a8-db3e-4829-8264-8ef59e08f069#tab_recordsView",
    imageSrc: require("./images/chlorophyllum_molybdites.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwj06OXOnIflAhXJT30KHU1RDJ8QjB16BAgBEAM&url=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fdweickhoff%2F5737201351&psig=AOvVaw3Y4NnVNBcftxxz8SS90NGI&ust=1570430587742620",
    characteristics: [
      "whitish hemispherical cap with coarse brownish scales",
      "white free gills",
      "green spore print",
    ],
    symptoms: [
      "vomiting",
      "diarrhoea",
      "colic",
    ],
    distribution: [
      "WA",
      "NT",
      "QLD",
      "NSW",
    ],
  },
  {
    latinName: "Amanita muscaria",
    commonName: "Fly Agaric",
    articleRef: "https://bie.ala.org.au/species/13d92830-593c-4fa3-a1c4-85aa80d124e6#tab_recordsView",
    imageSrc: require("./images/amanita_muscaria.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjE5ry5noflAhWESH0KHXTnBO0QjB16BAgBEAM&url=https%3A%2F%2Fwww.publicdomainpictures.net%2Fen%2Fview-image.php%3Fimage%3D232428%26picture%3Damanita-muscaria&psig=AOvVaw3Y5WK8FW-GYneqvQFI7v2W&ust=1570437635696395",
    characteristics: [
      "red cap with white pyramid-shaped warts. Sometimes the warts got washed off by rain",
      "yellowish layer of skin under veil",
      "white free gills and spore print",
      "bulb at the base with 2-4 distinct rings or ruffs",
    ],
    symptoms: [
      "nausea",
      "twitching",
      "drowsiness",
      "cholinergic crisis-like effects",
      "generally tripping",
      "ataxia",
      "loss of equilibrium",
      "delirium",
      "seizures",
      "coma",
      "sometimes retrograde amnesia and somnolence"
    ],
    distribution: [
      "WA",
      "NSW",
      "ACT",
      "SA",
      "TAS",
      "VIC",
    ],
  },
  {
    latinName: "Paxillus involutus",
    commonName: "Brown Roll-rim",
    articleRef: "https://bie.ala.org.au/species/57b90cbb-8dae-4280-8406-6d2a8aed5ce1",
    imageSrc: require("./images/paxillus_involutus.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjzsOmln4flAhXRT30KHai7AvMQjB16BAgBEAM&url=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Fatrnkoczy%2F36576899254&psig=AOvVaw3OnYODos-u0L8pzZHftl2O&ust=1570437803600487",
    characteristics: [
      "brown, funnel-shaped cap with an inroled rim and decurrent gills",
      "darkens when bruised",
      "brown spore print",
      "mild to faintly sour or sharp odour and taste",
    ],
    symptoms: [
      "vomiting",
      "diarrhoea",
      "abdominal pain",
      "decreased blood volume",
      "hemolysis, can lead to renal failure, shock, respiratory failure, and disseminated intravascular coagulation, even death"
    ],
    distribution: [
      "SA",
      "NSW",
      "VIC",
      "NSW",
    ],
  },
  {
    latinName: "Psilocybe subaeruginosa",
    commonName: "Copper Tops",
    articleRef: "https://bie.ala.org.au/species/1d9a1012-6e57-4fd0-8f00-ea10b2d62ecf#tab_recordsView",
    imageSrc: require("./images/psilocybe_subaeruginosa.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiU_9_uoYflAhVGWX0KHbLlBUMQjB16BAgBEAM&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3APsilocybe_subaeruginosa_Cleland_778362.jpg&psig=AOvVaw1zP6zrWrJ-iQao3WUGAJHx&ust=1570438153717966",
    characteristics: [
      "conical/convex, tan brown cap, margin striate when moist, uplifting in age",
      "blue when bruised",
      "dark violet brown spore print",
    ],
    symptoms: [
      "tripping",
    ],
    distribution: [
      "SA",
      "VIC",
      "NSW",
      "TAS",
    ],
  },
  {
    latinName: "Galerina marginata",
    commonName: "Funeral Bell",
    articleRef: "https://biocache.ala.org.au/occurrences/search?q=lsid%3A44a457df-2d08-4a93-ab09-273d03632358&fq=state%3A%22New+South+Wales%22#tab_recordsView",
    imageSrc: require("./images/galerina_marginata.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiDgO3bqIflAhVDT30KHZ9NBKUQjB16BAgBEAM&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AGalerina_marginata_582664.jpg&psig=AOvVaw3rcG00H24nLy4EwTFsl_T2&ust=1570440390180603",
    characteristics: [
      "convex/broadly conical cap, margins curved in against the gills",
      "when older, cap is breadly convex and flattened, sometimes with a central elevation",
      "membranous ring on the upper half of the stem near the cap",
      "rusty brown spore print",
    ],
    symptoms: [
      "abdominal pain",
      "vomiting",
      "diarrhoea",
      "gastrointestinal bleeding",
      "coma",
      "liver or kidney failure, leading to death",
    ],
    distribution: [
      "WA",
      "SA",
      "VIC",
      "TAS",
    ],
  },
  {
    latinName: "Gyromitra esculenta",
    commonName: "False Morel",
    articleRef: "https://bie.ala.org.au/species/c86c6d82-12a8-40c2-aafb-8e14d6f1bad4",
    imageSrc: require("./images/gyromitra_esculenta.jpg"),
    imageRef: "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjm8N_arIflAhUYb30KHT56BzwQjB16BAgBEAM&url=https%3A%2F%2Fes.wikipedia.org%2Fwiki%2FArchivo%3AGyromitra_esculenta_02.jpg&psig=AOvVaw3m14oLcMs3LgsGBmsPAc8e&ust=1570441513775235",
    characteristics: [
      "irregularly shaped cap, kinda like a brain, more wrinkled with age",
      "colour can be reddish, chesnut, purplish, bay-dark, or golden-brown",
      "solid stipe",
      "pleasant fruity smell",
      "whitish spore print",
    ],
    symptoms: [
      "nausea",
      "vomiting",
      "diarrhoea (possibly bloodstained)",
      "dizziness",
      "lethargy",
      "vertigo",
      "tremor",
      "ataxia",
      "nystagmus",
      "headaches",
      "liver or kidney damage, neurological dysfunction in some cases",
    ],
    distribution: [
      "TAS",
    ],
  },
];

export default data;
